name: GitHub Metrics

on:
  schedule: [{cron: "0 */12 * * *"}] # Runs every 12 hours
  workflow_dispatch: # Lets you trigger manually
  push:
    branches: ["main"]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub username
          username: GhBMpr 
          token: ${{ secrets.METRICS_TOKEN }}

          # Enable languages analysis
          plugin_languages: yes
          plugin_languages_ignored: ""
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_other: yes
          plugin_languages_limit: 100 # show ALL languages
          
          # Output file
          filename: github-metrics.svg
